### ISSUE TITLE
发现个小问题

### ISSUE THREAD

**Issue by weizhangCoder** [shaohuihu/HSSetTableViewController#1]
写的非常好，有个小问题 就是那个箭头ic_hs_tableView_arrow图片，当pod的时候，显示不出来，不知道你是否遇到。

**Comment by shaohuihu** [comment]
已经处理了 试下最新版本1.1.1  增加了富文本支持和一些细节处理。请更新试试

**Comment by shaohuihu** [comment]
@weizhangCoder 更新下版本试试
