### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by weizhangCoder** [shaohuihu/HSSetTableViewController#10]
因为我要自定义一种后面是textFiled的cell，我想继承HSCustomTableViewCell，但是pod下来头部好像没有这个.h,文件，这个怎么弄

**Comment by shaohuihu** [comment]
@weizhangCoder  有的 我才试了哦

**Comment by weizhangCoder** [comment]
方便留个QQ吗？请教下

**Comment by shaohuihu** [comment]
@weizhangCoder 714743449
