### ISSUE TITLE
Tab的frame问题？

### ISSUE THREAD

**Issue by ghost** [shaohuihu/HSSetTableViewController#12]
使用UIViewController分类， UIViewController里添加了其他的控件，怎么重写Tab的frame，使其不被遮挡一部分？

**Comment by shaohuihu** [comment]
@Doraemonyy 你好分类的tableView暂时不设置frame,如果你有其它视图。可以添加到自定义cell，或者 header 和footer 。刚升了下级，支持设置每个section的header视图。pod 下1.2.1，如有问题继续联系！

**Comment by ghost** [comment]
很感谢作者的回复，添加到自定义cell，或者 header 和footer ，控件会随着Tab上下滑动，有没有思路解决这个问题？

**Comment by shaohuihu** [comment]
@Doraemonyy   你好这个初始化完成后可以修改tableView的约束，比如修改高度。其它类似！
 for(NSLayoutConstraint *layout in self.view.constraints){
        if([layout.firstItem isEqual:self.hs_tableView] && layout.firstAttribute == NSLayoutAttributeHeight){
            //这是遍历到tableView的高度约束
            layout.constant -= 200;
            [self.view updateConstraints];
        }
        
    }

**Comment by ghost** [comment]
作者你好！ 我在分类UIViewController+HSSetTableView.h 增加- (void)setupTableViewConstrint;方法，
然后在使用分类的控制器里重写self.hs_tableView.frame 可是实现重写Tab的位置。不知道是否合理？

**Comment by shaohuihu** [comment]
@Doraemonyy   你好。这样不合理的哈，分类不是继承。因为一般你这种需求太少了，如果要调整按照我建议的方式调整下吧，增加不了多少代码。

**Comment by ghost** [comment]
谢谢作者！但是我个人觉得重写Tab的位置（约束）应该单独有一个方法才合理。

**Comment by shaohuihu** [comment]
@Doraemonyy  下个版本提供一个方法

**Comment by shaohuihu** [comment]
@ghost 请查看最新版本1.3.0分类可以设置。优化了一些细节
