### ISSUE TITLE
如何优雅的刷新整个列表？

### ISSUE THREAD

**Issue by ghost** [shaohuihu/HSSetTableViewController#19]
我使用作者的这个库，作为一个列表信息展示，数据根据请求会经常改变，
我是将创建列表放在一个方法里面 ，每次请求数据了都需要重新调用该方法，
系统的[self.TableView reloadData]; 并不会刷新。还是有其他的方式实现？

**Comment by fzschb** [comment]
不是执行reloadDate，是执行self updateCellModel方法

发自我的 iPhone

**Comment by ghost** [comment]
刷新整个列表呢？

**Comment by shaohuihu** [comment]
@cocoafanbin  updateCellModel 更新单个   reloadData更新全部 我demo中updateCellModel换成reloadData也没问题。reload之前确定model 是否更新
