### ISSUE TITLE
更新cell上的数据

### ISSUE THREAD

**Issue by ghost** [shaohuihu/HSSetTableViewController#2]
你好，你的作品很好，，但是有个问题，我从后台得到数据后怎么刷新cell上的内容？

**Comment by shaohuihu** [comment]
@AaronFanbin  你好  只需要 调用update方法，就可以完成更新    方法在HSSetTableViewMainController 
/**
 更新cell模型方法

 @param cellModel model
 */
- (void)updateCellModel:(HSBaseCellModel *)cellModel;
