### ISSUE TITLE
希望增加一个可以纯文本cell，cell里面的文本是居中的

### ISSUE THREAD

**Issue by amin168** [shaohuihu/HSSetTableViewController#6]
虽然可以重写一个，但如果有集成的就非常好啦

**Comment by shaohuihu** [comment]
@amin168   你好什么类型的APP，我去看看。

**Comment by amin168** [comment]
@shaohuihu 微信->设置->有个退出登录的按钮，就是这个按钮的样式啦，你看看😁

**Comment by shaohuihu** [comment]
@amin168  这种做成footer ，做成按钮吧，有的宽度也不一定的。如果不需要滑动加到self.view上

**Comment by shaohuihu** [comment]
@amin168   近期会支持。最近还会支持自定义cell

**Comment by amin168** [comment]
@shaohuihu 好的，我现在也是暂时用footer代替

**Comment by shaohuihu** [comment]
@amin168 已更新版本，居中的话只需要设置属性，而且还增加了自定义cell，一般可以不用header和footer，请参考demo。

**Comment by amin168** [comment]
@shaohuihu 辛苦啦，已经看见demo了，这个issues我就关闭啦
