### ISSUE TITLE
iOS8 的系统下奔溃

### ISSUE THREAD

**Issue by weizhangCoder** [shaohuihu/HSSetTableViewController#7]
Deployment tagrget 设置为8.0  然后再8.1的模拟器下面运行，会奔溃到下面的代码
  #ifdef NSFoundationVersionNumber_iOS_9_x_Max
    tableView.cellLayoutMarginsFollowReadableWidth = NO;
    #endif

**Comment by shaohuihu** [comment]
@weizhangCoder  谢谢指正 ,最新版1.1.6版本已解决。更新下试试

**Comment by weizhangCoder** [comment]
发现。1.1.3到1.5版本变化挺大的，原来返回的ctionBlock:^(HSBaseCellModel *model)这个模型中可以获取到Title和detailText 。现在的版本获取不到这两个属性了。

**Comment by shaohuihu** [comment]
@weizhangCoder   返回基类，子类对象指向基类指针嘛。这个完全是做成统一，你强制转下就可以了哈，就像聊天消息一样，都是返回base。Title和detailText 没有放在最基类了，结构发生了变化。现在1.1.6 这个目前是结构稳定版本，如有不明白继续联系我！

**Comment by shaohuihu** [comment]
@weizhangCoder 你看下最新demo
