### ISSUE TITLE
小需求！

### ISSUE THREAD

**Issue by ghost** [shaohuihu/HSSetTableViewController#8]
很喜欢你这个demo，很赞！！！

希望可以在  我(仿微信）里的  '设置'后面添加小红点提醒功能 ，并增加控制显示和隐藏的开关。（微信里面这样的提示功能）

**Comment by shaohuihu** [comment]
@AaronFanbin  可以用这个方法实现。为了兼容其它App目前这个方法可用
 /**
 model初始化方法
 
 @param attributeTitle 模型富文本标题
 @param block block回调
 @return HSBaseCellModel
 */
- (instancetype)initWithAttributeTitle:(NSAttributedString *)attributeTitle actionBlock:(ClickActionBlock)block;
